prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix cwl: <https://w3id.org/cwl/cwl#>
prefix toolreg: <http://ga4gh.org/schemas/tool-registry-schemas#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix sld: <https://w3id.org/cwl/salad#>

SELECT distinct ?p
WHERE {
  ?s ?p ?o .
}
LIMIT 250
